Add help command

diff --git a/HOME/.bashrc.d/02_utils b/HOME/.bashrc.d/02_utils
--- a/HOME/.bashrc.d/02_utils
+++ b/HOME/.bashrc.d/02_utils
@@ -83,9 +83,11 @@ function _:draw_tree_set_root() {
 }
 
 function _:draw_tree_update_leaves() {
-    local level=${1:-0}
-    local node=${2:-0}
+    local level
+    local node
 
+    level=${1:-0}
+    node=${2:-0}
     # Offspring has been added?
     if [[ ${level} -gt ${__CURRENT_TREE_LEVEL} ]]; then
         # Parent is no longer a leaf
@@ -104,10 +106,11 @@ function _:draw_tree_update_leaves() {
 }
 
 function _:draw_tree_append_nodes() {
-    local index=${1:-0}
+    local index
     local lindex
     local linfo
 
+    index=${1:-0}
     while [[ ${index} -lt ${#__TREE_PATH[@]} ]]; do
         lindex=${#__TREE_DATA[@]}
         __TREE_DATA+=( "${index}:${__TREE_PATH[${index}]}" )
@@ -122,13 +125,17 @@ function _:draw_tree_append_nodes() {
 }
 
 function _:draw_tree_insert_nodes() {
-    local index=${1:-0}
-    local lindex=${#__TREE_DATA[@]}
+    local index
+    local lindex
     local linfo
+
+    index=${1:-0}
+    lindex=${#__TREE_DATA[@]}
 
     # Emit node
     __TREE_DATA+=( "${index}:${__TREE_PATH[${index}]}" )
     _:draw_tree_update_leaves ${index} ${lindex}
+
     # Update last
     linfo="${__TREE_LEVELS[${index}]}"
     linfo="${linfo%,}"
@@ -149,13 +156,14 @@ function _:draw_tree_insert_nodes() {
 }
 
 function _:draw_tree_add_subtree() {
-    local index=0
+    local index
 
     # `$1` is either in a form `./a/b/c` or `a/b/c` and it must come from
     # a lexicographical-sorted source without duplicated items.
     IFS='/' read -r -a __TREE_PATH <<< "${1#./}"
 
     # Find the point of divergence:
+    index=0
     while [ \
         ${index} -lt ${#__TREE_PATH[@]} \
         -a "${__TREE_PATH[${index}]}" = "${__CURRENT_TREE_PATH[${index}]}" \
@@ -204,12 +212,17 @@ function _:draw_tree_root() {
 }
 
 function _:draw_tree_branch() {
-    local level=${1:-0}
-    local label="${2:-}"
-    shift 2
-    local args=( "$@" )
+    local level
+    local label
+    declare -a args
     local index
     local indent
+    local mode
+
+    level=${1:-0}
+    label="${2:-}"
+    shift 2
+    args=( "$@" )
 
     for mode in branch gap; do
         index=0
@@ -271,11 +284,14 @@ function _:draw_tree_branch() {
 }
 
 function _:draw_tree_annotation() {
-    local annotation="${1:-}"
-    local drew="${2:-}"
+    local annotation
+    local drew
+    local indent
+
+    annotation="${1:-}"
+    drew="${2:-}"
     shift 2
-    local index=0
-    local indent="  "
+    indent="  "
 
     echo -ne "$(_:color cyan)"
     while [[ $# -gt 0 ]]; do
@@ -314,8 +330,9 @@ function _:draw_tree_annotation() {
 }
 
 function _:draw_tree_close_annotation() {
-    local indent="  "
+    local indent
 
+    indent="  "
     echo -ne "$(_:color cyan)"
     while [[ $# -gt 0 ]]; do
         case "${1:-}" in
@@ -342,14 +359,17 @@ function _:draw_tree_close_annotation() {
 }
 
 function _:draw_tree() {
-    local index=0
-    local next=0
-    local state=()
+    local index
+    local next
+    declare -a state
     local item
-    local level=0
-    local label=""
-    local drew=""
+    local level
+    local label
+    local drew
 
+    index=0
+    state=()
+    drew=""
     while [[ ${index} -lt ${#__TREE_DATA[@]} ]]; do
         item="${__TREE_DATA[${index}]}"
         if [[ "${item}" =~ ^R:(.*)$ ]]; then
@@ -459,7 +479,7 @@ function u:error() {
 
 function u:die() {
     local opts
-    local exitcode=1
+    local exitcode
 
     opts=$(
         while [[ $# -gt 0 ]]; do
@@ -489,6 +509,8 @@ function u:die() {
 
     eval set -- "${opts}"
 
+    exitcode=1
+
     while [[ $# -gt 0 ]]; do
         case "${1:-}" in
             -h | --help)
@@ -513,7 +535,7 @@ function u:die() {
                 return 0
             ;;
             --exitcode)
-                exitcode="${2:-1}"
+                exitcode=${2:-1}
                 shift 2
             ;;
             --)
@@ -534,6 +556,124 @@ function u:die() {
     exit ${exitcode}
 }
 
+function _:generate_help() {
+    local sources
+    local source
+    local command
+    local help
+
+    readarray -t sources < <(find . -type f -print | sort | uniq)
+
+    for source in "${sources[@]}"; do
+        while read -r; do
+            if [[ "${REPLY}" =~ ^function[\ ]+([a-z]+:[^\(]*) ]]; then
+                command="${BASH_REMATCH[1]}"
+                help="$("${command}" --help | sed '2q;d')"
+                printf '%-20s%s\n' "${command}" "${help}"
+            fi
+        done < "${source}"
+    done
+}
+
+function _:generate_help_script() {
+    cat <<-_EOF
+	# Help (automatically generated by \`${1:-}\`)
+
+	function _:help() {
+	    cat <<-EOF
+	_EOF
+
+    while read -r; do
+        echo "	${REPLY}"
+    done < <(_:generate_help | sort)
+
+    printf '\tEOF\n}\n'
+}
+
 function u:build_help() (
-    :
+    local opts
+
+    opts=$(
+        getopt \
+            --options h \
+            --longoptions help \
+            --name ${FUNCNAME[0]} \
+            -- \
+            "$@" 2> >(while read -r; do _:error ${REPLY}; done)
+    )
+
+    if [[ $? -ne 0 ]]; then
+        u:die
+    fi
+
+    eval set -- "${opts}"
+
+    while [[ $# -gt 0 ]]; do
+        case "${1:-}" in
+            -h | --help)
+                echo "Usage: ${FUNCNAME[0]} [-h|--help]"
+                echo "Build a help"
+                echo ""
+                echo "Options:"
+                echo "  -h, --help    print this screen and exit"
+                u:die -0
+            ;;
+            --)
+                shift
+                break
+            ;;
+            *)
+                u:die "${FUNCNAME[0]}: Internal error"
+            ;;
+        esac
+    done
+
+    cd "${HOME}/.bashrc.d" || u:die --exitcode $?
+
+    _:generate_help_script "${FUNCNAME[0]}" > "./99_help"
 )
+
+function help:() {
+    local opts
+
+    opts=$(
+        getopt \
+            --options h \
+            --longoptions help \
+            --name ${FUNCNAME[0]} \
+            -- \
+            "$@" 2> >(while read -r; do _:error ${REPLY}; done)
+    )
+
+    if [[ $? -ne 0 ]]; then
+        return 1
+    fi
+
+    eval set -- "${opts}"
+
+    while [[ $# -gt 0 ]]; do
+        case "${1:-}" in
+            -h | --help)
+                echo "Usage: ${FUNCNAME[0]} [-h|--help] [COMMAND]"
+                echo "Get a help"
+                echo ""
+                echo "With no arguments, print a list of all commands. If"
+                echo "COMMAND is provided, print the help for it."
+                echo ""
+                echo "Options:"
+                echo "  -h, --help    print this screen and exit"
+                return 0
+            ;;
+            --)
+                shift
+                break
+            ;;
+            *)
+                _:error "${FUNCNAME[0]}: Internal error"
+                return 1
+            ;;
+        esac
+    done
+
+    "${1:-_:help}" --help
+}
